# Generated by Django 3.2.5 on 2021-07-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('air2_5', models.FloatField(default=0)),
                ('description', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
