# Generated by Django 3.2.5 on 2021-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_alter_location_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_air', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='resoure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.ManyToManyField(blank=True, to='weather_app.Category'),
        ),
        migrations.AddField(
            model_name='location',
            name='resoure',
            field=models.ManyToManyField(blank=True, to='weather_app.resoure'),
        ),
    ]
